# Generated by Django 4.2.11 on 2026-09-03 03:22

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no site (1 vem primeiro)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Frutas, Cremes, Coberturas, Chocolates, etc.', max_length=100)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição nas opções (1 vem primeiro)')),
            ],
            options={
                'verbose_name': 'Categoria de Adicional',
                'verbose_name_plural': 'Categorias de Adicionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Escolha a Base, Onde ficam os complementos?, Adicionais Grátis, etc.', max_length=100)),
                ('qtd_minima', models.IntegerField(default=0, help_text='0 = Opcional (ex: Descartáveis). 1 ou + = Obrigatório (ex: Escolha a Base)')),
                ('qtd_maxima', models.IntegerField(default=1, help_text='Máximo de escolhas inclusas no preço ou permitidas no grupo')),
                ('permitir_repeticao', models.BooleanField(default=True, help_text='Se marcado, permite escolher 2x ou mais do MESMO item (ex: 2x Bombom). Se desmarcado, cada item só pode 1x.')),
                ('permitir_exceder', models.BooleanField(default=False, help_text='Se marcado, permite ao cliente selecionar mais itens que a qtd_maxima cobrando valor extra')),
                ('preco_item_excedente', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço cobrado por CADA item adicional que ultrapassar a qtd_maxima', max_digits=6)),
                ('limite_excedente', models.IntegerField(default=0, help_text='Quantidade MÁXIMA de itens EXTRAS que o cliente pode adicionar além da qtd_maxima')),
                ('cobrar_camada_extra', models.BooleanField(default=False, help_text='Se marcado, 1ª seleção é grátis e da 2ª em diante cobra o valor de preco_camada_extra configurado no produto.')),
            ],
            options={
                'verbose_name': 'Grupo de Opções',
                'verbose_name_plural': 'Grupos de Opções',
            },
        ),
        migrations.CreateModel(
            name='ItemAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, help_text='Faça upload da imagem diretamente para o Cloudinary ou selecione da sua mídia.', max_length=255, null=True, verbose_name='imagem')),
                ('disponibilidade', models.CharField(choices=[('disponivel', 'Disponível'), ('esgotado', 'Esgotado (Exibe acinzentado/sem estoque)'), ('oculto', 'Oculto (Esconde totalmente do cliente)')], default='disponivel', help_text='Controla se o item aparece disponível, acinzentado (sem estoque) ou oculto para o cliente.', max_length=20)),
                ('categoria_item', models.ForeignKey(blank=True, help_text='Selecione o grupo (ex: Frutas, Cremes, Coberturas) para organizar no cardápio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='loja.categoriaitemadicional', verbose_name='Categoria do Adicional')),
            ],
            options={
                'verbose_name': 'Item Adicional / Opção',
                'verbose_name_plural': 'Itens Adicionais / Opções',
                'ordering': ['categoria_item__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemGrupoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_especifico', models.DecimalField(decimal_places=2, default=0.0, help_text='Preço do item para este grupo especificamente (ex: Nutella no 330ml vs 770ml)', max_digits=6)),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Define a ordem de exibição deste item DENTRO deste grupo (1 vem primeiro)')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_relacionados', to='loja.grupoopcao')),
            ],
            options={
                'verbose_name': 'Item do Grupo',
                'verbose_name_plural': 'Itens dos Grupos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('endereco_completo', models.JSONField()),
                ('payload_itens', models.JSONField()),
                ('valor_produtos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('taxa_entrega', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('mercado_pago_id', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição dos ingredientes para combos ou produtos fixos')),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_camada_extra', models.DecimalField(decimal_places=2, default=2.0, help_text="Valor cobrado por cada camada extra selecionada em grupos com 'cobrar_camada_extra' ativo.", max_digits=6)),
                ('eh_customizavel', models.BooleanField(default=True, help_text='Desmarque para produtos/combos com receita fixa (não abre o modal step-by-step)')),
                ('eh_combo', models.BooleanField(default=False, help_text='Marque se for um combo promocional')),
                ('imagem', cloudinary.models.CloudinaryField(blank=True, help_text='Faça upload da imagem principal do produto no Cloudinary.', max_length=255, null=True, verbose_name='imagem')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProdutoGrupoOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem exata de exibição deste grupo para ESTE produto (1 = Primeiro do topo)')),
                ('grupo_opcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.grupoopcao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
            options={
                'verbose_name': 'Grupo de Opção do Produto',
                'verbose_name_plural': 'Grupos de Opções do Produto',
                'ordering': ['ordem'],
                'unique_together': {('produto', 'grupo_opcao')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='grupos_opcoes',
            field=models.ManyToManyField(blank=True, help_text='Grupos de opções PRINCIPAIS que aparecem no produto, com ordem definida.', through='loja.ProdutoGrupoOpcao', to='loja.grupoopcao'),
        ),
        migrations.CreateModel(
            name='ItemGrupoOpcaoFilho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem em que este subgrupo aparece quando a opção pai é selecionada')),
                ('grupo_filho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.grupoopcao')),
                ('item_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.itemgrupoopcao')),
            ],
            options={
                'verbose_name': 'Subgrupo Condicional',
                'verbose_name_plural': 'Subgrupos Condicionais',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='itemgrupoopcao',
            name='grupos_filhos',
            field=models.ManyToManyField(blank=True, help_text="Subgrupos que abrem automaticamente quando esta opção é selecionada (ex: Selecionar 'Sorvete' abre 'Sabores de Sorvete').", related_name='itens_pai', through='loja.ItemGrupoOpcaoFilho', to='loja.grupoopcao'),
        ),
        migrations.AddField(
            model_name='itemgrupoopcao',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.itemadicional'),
        ),
        migrations.CreateModel(
            name='ItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, help_text='Quantas unidades deste produto vêm no combo (ex: 2 para 2 copos de 330ml)')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Ordem de personalização no frontend (1 = Copo 1, 2 = Copo 2, etc.)')),
                ('combo', models.ForeignKey(help_text='O produto principal marcado como eh_combo=True', on_delete=django.db.models.deletion.CASCADE, related_name='itens_combo', to='loja.produto')),
                ('produto_conteudo', models.ForeignKey(help_text='Selecione um produto existente (ex: Copo 330ml) que fará parte deste combo.', on_delete=django.db.models.deletion.CASCADE, related_name='presente_em_combos', to='loja.produto', verbose_name='Produto Incluído')),
            ],
            options={
                'verbose_name': 'Item do Combo',
                'verbose_name_plural': 'Itens do Combo',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemgrupoopcao',
            unique_together={('grupo', 'item')},
        ),
    ]
